//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediaManagerEntities : DbContext
    {
        public MediaManagerEntities()
            : base("name=MediaManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Format> Formats { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MPAARating> MPAARatings { get; set; }
        public virtual DbSet<Own> Owns { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
